spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    username: ahian
    password: ahian
    url: jdbc:postgresql://localhost:5432/interside
  jpa:
    open-in-view: false
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect